version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "news-nugget"
      POSTGRES_USER: "mayank"
      POSTGRES_PASSWORD: "mayank@14"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
